use_frameworks!

platform :ios, '8.0'

target 'SFKeyChainKit_Example' do
  pod 'SFKeyChainKit', :path => '../'

  target 'SFKeyChainKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
